---
common:
  packages:
  - sudo
  - git
  - nano
  - curl
  - unzip

apache_listen_port: 80
apache_vhosts_filename: "mutov-slingr.votum-local.de.conf"
apache_remove_default_vhost: true
apache_vhosts:
  - servername: "api.mutov-slingr.votum-local.de"
    documentroot: "/var/www/mutov-slingr/web/api"
  - servername: "gui.mutov-slingr.votum-local.de"
    documentroot: "/var/www/mutov-slingr/web"
  - servername: "mutov-slingr.votum-local.de"
    documentroot: "/var/www/mutov-slingr/app/web"
  - servername: "magento.mutov-slingr.votum-local.de"
    documentroot: "/var/www/magento"
apache_user: vagrant
apache_group: www-data

mysql_root_password: root
mysql_databases:
  - name: slingr
    encoding: utf8
    collation: utf8_general_ci
    dump_file: ansible/environments/dev/slingr.sql.gz
  - name: magento
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: slingr
    host: "%"
    password: slingr
    priv: "*.*:ALL"
mysql_packages:
  - mariadb-server
mysql_daemon: mysql
mysql_log_error: /var/log/mysql/mysql.log
mysql_syslog_tag: mysqld
mysql_pid_file: /var/run/mysqld/mysqld.pid

php_version: "5.6"
php_opcache_enable: "0"
php_enable_apc: true
php_memory_limit: "256M"
php_display_errors: "On"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - libapache2-mod-php5
  - php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-gd
  - php5-mysql
  - php5-xdebug
  - php-apc

project_root: "{{ apache_vhosts[0].documentroot }}"

# GitHub OAuth token (used to help overcome API rate limits).
composer_github_oauth_token: 'd4faa577b24e168bffc74bb7dd50600edd563db1'
composer_home_owner: vagrant
composer_home_group: vagrant

magento_version: "1.9.2.4"
magento_download_host: "https://github.com/OpenMage/magento-mirror/archive/{{ magento_version }}"
magento_download_package: "magento-{{ magento_version }}.zip"
magento_install_tmp_dir_sub: "magento-mirror-{{ magento_version }}"
magento_webuser: 'vagrant'
magento_config:
   license_agreement_accepted: "yes"
   locale: "de_DE"
   timezone: "Europe/Berlin"
   default_currency: "EUR"
   db_host: "localhost"
   db_name: "magento"
   db_user: "{{ mysql_users.0.name }}"
   db_pass: "{{ mysql_users.0.password }}"
   url: "http://magento.mutov-slingr.votum-local.de/"
   use_rewrites: "yes"
   use_secure: "yes"
   secure_base_url: "http://magento.mutov-slingr.votum-local.de/"
   use_secure_admin: "yes"
   admin_firstname: "Magento"
   admin_lastname: "Admin"
   admin_email: "bernd.alter@bvotum.de"
   admin_username: "admin"
   admin_password: "magento123"
   skip_url_validation: "no"
magento_modman_extensions_git:
  - repo: https://github.com/votum/AvS_FastSimpleImport
    name: "AvS_FastSimpleImport"
    dest: /var/www/magento-extensions

prepare:
  settings_target: "/var/www/mutov-slingr/web"
  run_composer_install_in:
    - "/var/www/mutov-slingr"
